parameters:
- name: arch
  type: string

- name: machine_pool
  type: string

- name: base_image
  type: string

- name: devtoolset_rootpath
  type: string

- name: ld_library_path_arg
  type: string

- name: prepend_path
  type: string

- name: device
  type: string
  default: '-d CPU'

- name: with_cache
  type: boolean
  default: false

jobs:
- job: Linux_py_Wheels_${{ parameters.arch }}
  timeoutInMinutes: 240
  workspace:
    clean: all
  pool: ${{ parameters.machine_pool }}
  variables:
    # The build machine pool doesn't have dotnet, so it can't run CG.
    skipComponentGovernanceDetection: true
    ${{ if eq(parameters.with_cache, 'true') }}:
      ORT_CCACHE_DIR: $(Pipeline.Workspace)/ccache
  steps:
    - task: mspremier.PostBuildCleanup.PostBuildCleanup-task.PostBuildCleanup@3
      displayName: 'Clean Agent Directories'
      condition: always()

    - checkout: self
      clean: true
      submodules: none

    - template: set-nightly-build-option-variable-step.yml

    - template: get-docker-image-steps.yml
      parameters:
        Dockerfile: tools/ci_build/github/linux/docker/inference/x64/python/cpu/Dockerfile.manylinux2014_cpu
        Context: tools/ci_build/github/linux/docker/inference/x64/python/cpu
        DockerBuildArgs: "--build-arg BUILD_UID=$( id -u ) --build-arg BASEIMAGE=${{ parameters.base_image }} --build-arg PLATFORM=${{ parameters.arch }} --build-arg PREPEND_PATH=${{ parameters.prepend_path }} --build-arg LD_LIBRARY_PATH_ARG=${{ parameters.ld_library_path_arg }} --build-arg DEVTOOLSET_ROOTPATH=${{ parameters.devtoolset_rootpath }}"
        Repository: onnxruntimecpubuilpython${{ parameters.arch }}
        ${{ if eq(parameters.arch, 'aarch64') }}:
            UpdateDepsTxt: false

    - ${{ if eq(parameters.with_cache, 'true') }}:
      - template: linux-buildcache-in-container.yml
        parameters:
          TODAY: $(TODAY)
          AdditionalKey: $(Build.SourceBranchName)
          CACHE_DIR: $(ORT_CCACHE_DIR)
          BuildStep:
            - script: |
                mkdir -p $(ORT_CCACHE_DIR)
              displayName: create ccache directory in Host
            - task: Bash@3
              displayName: 'Build Python Wheel'
              inputs:
                targetType: filePath
                filePath: tools/ci_build/github/linux/run_python_dockerbuild.sh
                arguments: -a "--volume $(ORT_CCACHE_DIR):/cache -e CCACHE_DIR=/cache" -i onnxruntimecpubuilpython${{ parameters.arch }} -x "${{ parameters.device }}"
              env:
                ORT_BUILD_WITH_CACHE: 1
    - ${{ else }}:
      - task: Bash@3
        displayName: 'Build Python Wheel'
        inputs:
          targetType: filePath
          filePath: tools/ci_build/github/linux/run_python_dockerbuild.sh
          arguments: -i onnxruntimecpubuilpython${{ parameters.arch }} -x "${{ parameters.device }}"


    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: ONNXRuntime python wheel'
      inputs:
        PathtoPublish: '$(Build.BinariesDirectory)/dist'
        ArtifactName: onnxruntime

    - task: PublishPipelineArtifact@0
      displayName: 'Publish Test Binaries'
      inputs:
        artifactName: 'drop-linux-cpu-${{ parameters.arch }}'
        targetPath: '$(Build.BinariesDirectory)/Release'
